projects:
  app:
    schemaPath: 'src/schema.graphql'
    extensions:
      endpoints:
        default: 'http://192.168.1.2:4444'
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: prisma.yml
